on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
    
      - name: Checkout
        uses: actions/checkout@v5.0.0    

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
